### ISSUE TITLE
Bad Request Error when uploading apk

### ISSUE THREAD

**Issue by mmsysmm** [galonga/upload-amazon-appstore#128]
## :writing_hand: Describe the bug

Unable to upload APK with Bad Request Error

## :bomb: Steps to reproduce

Upload to amazon appstore as apk.

## :camera: Screenshots

```
##[group***Run galonga/***-amazon-appstore@v1.0.3
with:
  clientId: ***
  clientSecret: ***
  appId: ***
  releaseFile: app/build/outputs/apk/release/******.apk
env:
  JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/11.0.19-7/x6
  PACKAGE_NAME: ***
##[endgroup***
Getting Authentication Token
Checking if an open Edit exists
Open edit found
Found apk with version code 71 - id M1I[5] 4SU7XWU - APK1
##[error***Failed to *** apk due to [Error*** Bad Request
```

## :iphone: Tech info
 - Gradle version: 
 - Script version:

**Comment by galonga** [comment]
Looks like you already have an upcoming version in you console. You need to delete this one first.

**Comment by mmsysmm** [comment]
Thanks for your reply.
At the time I raised the issue, there was an issue with the Amazon Submission API and I contacted Amazon and they resolved it.
